### ISSUE TITLE
Hardware Definition -GIO Ports

### ISSUE THREAD

**Issue by JorgeLopezCasillas** [marlen6457/Proyecto_Integrador_DSE_2019#2]
### Hardware Definition.

**This Issue includes two parts: Documentation + Confirmation** 

**Documentation**:

**Make a table with next points.**

- [x] Each Input/Output  pin defined with port assigned
- [x] Description.

- [x] Datatype (Analogic, digital, etc).

- [ ] Add EMCS BDF for all the load required.

`This information shall be upload in a folder of repository EMCS_SysReq`

**Confirmation**:

- [ ] Reading push button input.  

`This has to check for every member of the team`.

**Comment by JPRMEXDI** [comment]
*Add EMCS BFD

**Comment by JorgeLopezCasillas** [comment]
[Pin Definition.xlsx](https://github.com/marlen6457/Proyecto_Integrador_DSE_2019/files/2959107/Pin.Definition.xlsx)
