### ISSUE TITLE
CPU initialization  

### ISSUE THREAD

**Issue by JPRMEXDI** [marlen6457/Proyecto_Integrador_DSE_2019#3]
**CPU Initialization**
- [ ] Clock settings due to project requirements

- [ ] Timer Interrupt. `Comment which Channel Timer was selected`

- [ ] TIC'S per task

- [ ] Create a Main Thread

**Comment by JorgeLopezCasillas** [comment]
This task or issue is intended to initialize the microcontroller. 
Set the TIC's per task in the main loop
