### ISSUE TITLE
Measurement feedback signal-RPM 

### ISSUE THREAD

**Issue by JPRMEXDI** [marlen6457/Proyecto_Integrador_DSE_2019#8]
- [x] Reading RPM´s on the fan motor using an oscilloscope.  

- [x] Finally, reading RPM signal fan motor within micro´s pin.  

- [x] Set an input capture. Public the input port

**Comment by JorgeLopezCasillas** [comment]
RPM   pulses signal input | Port 1 Pin 3


[Caracterización Motor DC.xlsx](https://github.com/marlen6457/Proyecto_Integrador_DSE_2019/files/2959624/Caracterizacion.Motor.DC.xlsx)

**Comment by JorgeLopezCasillas** [comment]
![RPM Pulses_100Hz PWM](https://user-images.githubusercontent.com/27788862/54251039-9fd4f000-450b-11e9-8c11-cae660e94c14.jpg)
